# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 22:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('constants', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExchangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.IntegerField(default=0, verbose_name='Сколько пользователь захотел обменять баллов')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 1, 5, 0, 35, 19, 926170), verbose_name='Дата обмена')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('gender', models.CharField(choices=[(' ', 'Выбрать...'), ('male', 'Мужчина'), ('female', 'Женщина')], default=' ', max_length=8, verbose_name='Пол')),
                ('curing_form', models.CharField(choices=[(' ', 'Выбрать...'), ('stationar', 'Cтационарное'), ('poliklinika', 'Поликлиническое')], default=' ', max_length=15, verbose_name='Форма лечения')),
                ('category', models.CharField(choices=[(' ', 'Выбрать...'), ('first', 'Первая'), ('second', 'Вторая'), ('no_category', 'Без категории')], default=' ', max_length=15, verbose_name='Категория')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('date_of_birth', models.DateField(default=datetime.date(1970, 1, 1), verbose_name='Дата рождения')),
                ('main_phone', models.CharField(blank=True, max_length=12, verbose_name='Моб. телефон 1')),
                ('secondary_phone', models.CharField(blank=True, max_length=12, verbose_name='Моб. телефон 2')),
                ('work_phone', models.CharField(blank=True, max_length=12, verbose_name='Рабочий телефон')),
                ('bed_quantity', models.IntegerField(default=0, verbose_name='Кол-во койко-мест')),
                ('patient_quantity', models.IntegerField(default=0, verbose_name='Кол-во пациентов в месяц')),
                ('district', models.CharField(default=' ', max_length=20, verbose_name='Район')),
                ('house', models.CharField(default=' ', max_length=5, verbose_name='Дом')),
                ('flat', models.IntegerField(default=0, verbose_name='Квартира')),
                ('index', models.IntegerField(default=0, verbose_name='Индекс')),
                ('score', models.IntegerField(default=0, verbose_name='Баллы')),
                ('area', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='constants.Area', verbose_name='Область')),
                ('city', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='constants.City', verbose_name='Город')),
                # ('position', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constants.Position', verbose_name='Должность')),
                ('speciality', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='constants.Speciality', verbose_name='Специальность')),
                ('work', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='constants.Hospital', verbose_name='Место работы')),
            ],
        ),
        migrations.AddField(
            model_name='userexchangehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
