# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 12:14
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constants', '__first__'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExchangeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange', models.IntegerField(default=0, verbose_name='Сколько пользователь захотел обменять баллов')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обмена')),
            ],
        ),
        migrations.CreateModel(
            name='UserFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название группы')),
                ('gender', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=16, verbose_name='Пол')),
                ('age_from', models.IntegerField(blank=True, null=True, verbose_name='Возраст от')),
                ('age_to', models.IntegerField(blank=True, null=True, verbose_name='Возраст до')),
                ('bed_quantity_from', models.IntegerField(blank=True, null=True, verbose_name='Кол-во койко-мест от')),
                ('bed_quantity_to', models.IntegerField(blank=True, null=True, verbose_name='Кол-во койко-мест до')),
                ('patient_quantity_from', models.IntegerField(blank=True, null=True, verbose_name='Кол-во пациентов в месяц от')),
                ('patient_quantity_to', models.IntegerField(blank=True, null=True, verbose_name='Кол-во пациентов в месяц до')),
                ('area', models.ManyToManyField(blank=True, to='constants.Area', verbose_name='Область')),
                ('category', models.ManyToManyField(blank=True, default=None, to='constants.Category', verbose_name='Категория')),
                ('city', models.ManyToManyField(blank=True, to='constants.City', verbose_name='Город')),
                ('curing_form', models.ManyToManyField(blank=True, default=None, to='constants.CuringForm', verbose_name='Форма лечения')),
                ('position', models.ManyToManyField(blank=True, default=None, to='constants.Position', verbose_name='Должность')),
                ('speciality', models.ManyToManyField(blank=True, to='constants.Speciality', verbose_name='Специальность')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('patronimyc', models.CharField(max_length=17, verbose_name='Отчество')),
                ('gender', models.CharField(choices=[(' ', 'Выбрать...'), ('male', 'Мужчина'), ('female', 'Женщина')], max_length=8, verbose_name='Пол')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('date_of_birth', models.DateField(default=datetime.date(1970, 1, 1), null=True, verbose_name='Дата рождения')),
                ('main_phone', models.CharField(blank=True, max_length=13, verbose_name='Моб. телефон 1')),
                ('secondary_phone', models.CharField(blank=True, max_length=13, verbose_name='Моб. телефон 2')),
                ('work_phone', models.CharField(blank=True, max_length=13, verbose_name='Рабочий телефон')),
                ('bed_quantity', models.IntegerField(default=0, verbose_name='Кол-во койко-мест')),
                ('patient_quantity', models.IntegerField(default=0, verbose_name='Кол-во пациентов в месяц')),
                ('district', models.CharField(max_length=20, verbose_name='Район')),
                ('house', models.CharField(max_length=5, verbose_name='Дом')),
                ('flat', models.IntegerField(default=0, verbose_name='Квартира')),
                ('index', models.IntegerField(default=0, verbose_name='Индекс')),
                ('score', models.IntegerField(default=0, verbose_name='Баллы')),
                ('total_score', models.IntegerField(default=0, verbose_name='Баллов за всё время')),
                ('total_exchange', models.IntegerField(default=0, verbose_name='Баллов обменяно за всё время')),
                ('user_agreed', models.BooleanField(default=False, verbose_name='Согласие пользователя')),
                ('area', models.ForeignKey(to='constants.Area', verbose_name='Область')),
                ('category', models.ForeignKey(to='constants.Category', verbose_name='Категория')),
                ('city', models.ForeignKey(to='constants.City', verbose_name='Город')),
                ('curing_form', models.ForeignKey(to='constants.CuringForm', verbose_name='Форма лечения')),
                ('position', models.ForeignKey(related_name='+', to='constants.Position', verbose_name='Должность')),
                ('speciality', models.ForeignKey( to='constants.Speciality', verbose_name='Специальность')),
                ('work', models.ForeignKey( to='constants.Hospital', verbose_name='Место работы')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DurationField(verbose_name='Длительность сеанса')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время сеанса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='userfilter',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='users.UserProfile', verbose_name='Пользователи в группе'),
        ),
        migrations.AddField(
            model_name='userfilter',
            name='work',
            field=models.ManyToManyField(blank=True, to='constants.Hospital', verbose_name='Место работы'),
        ),
        migrations.AddField(
            model_name='userexchangehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
