# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='additional_speciality',
            field=models.ManyToManyField(related_name='extra_speciality', to='constants.Speciality', verbose_name='Дополнительные специальности'),
        ),
    ]
