# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 22:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0001_initial'),
        ('users', '0002_auto_20160105_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название группы')),
                ('gender', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(' ', 'Выбрать...'), ('male', 'Мужчина'), ('female', 'Женщина')], max_length=8, verbose_name='Пол')),
                ('curing_form', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(' ', 'Выбрать...'), ('stationar', 'Cтационарное'), ('poliklinika', 'Поликлиническое')], max_length=15, verbose_name='Форма лечения')),
                ('category', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(' ', 'Выбрать...'), ('first', 'Первая'), ('second', 'Вторая'), ('no_category', 'Без категории')], default=' ', max_length=15, verbose_name='Категория')),
                ('age_from', models.IntegerField(blank=True, verbose_name='Возраст от')),
                ('age_to', models.IntegerField(blank=True, verbose_name='Возраст от')),
                ('bed_quantity_from', models.IntegerField(blank=True, verbose_name='Кол-во койко-мест от')),
                ('bed_quantity_to', models.IntegerField(blank=True, verbose_name='Кол-во койко-мест до')),
                ('patient_quantity_from', models.IntegerField(blank=True, verbose_name='Кол-во пациентов в месяц от')),
                ('patient_quantity_to', models.IntegerField(blank=True, verbose_name='Кол-во пациентов в месяц до')),
                ('area', models.ManyToManyField(blank=True, default=' ', to='constants.Area', verbose_name='Область')),
                ('city', models.ManyToManyField(blank=True, default=' ', to='constants.City', verbose_name='Город')),
                ('position', models.ManyToManyField(blank=True, default=' ', related_name='_userfilter_position_+', to='constants.Position', verbose_name='Должность')),
                ('speciality', models.ManyToManyField(blank=True, default=' ', to='constants.Speciality', verbose_name='Специальность')),
                ('work', models.ManyToManyField(blank=True, default=' ', to='constants.Hospital', verbose_name='Место работы')),
            ],
        ),
        migrations.AlterField(
            model_name='userexchangehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 6, 0, 51, 19, 559737), verbose_name='Дата обмена'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='main_phone',
            field=models.CharField(blank=True, max_length=13, verbose_name='Моб. телефон 1'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=13, verbose_name='Моб. телефон 2'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_phone',
            field=models.CharField(blank=True, max_length=13, verbose_name='Рабочий телефон'),
        ),
    ]
