# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_additional_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='additional_speciality',
            field=models.ManyToManyField(blank=True, related_name='extra_speciality', to='constants.Speciality', verbose_name='Дополнительные специальности'),
        ),
    ]
