# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170406_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='additional_speciality',
            field=models.ManyToManyField(blank=True, default=' ', null=True, related_name='extra_speciality', to='constants.Speciality', verbose_name='Дополнительные специальности'),
        ),
    ]
