# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 22:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170422_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilter',
            name='area',
            field=models.ManyToManyField(blank=True, null=True, to='constants.Area', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='category',
            field=models.ManyToManyField(blank=True, to='constants.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='city',
            field=models.ManyToManyField(blank=True, null=True, to='constants.City', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='curing_form',
            field=models.ManyToManyField(blank=True, null=True, to='constants.CuringForm', verbose_name='Форма лечения'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='position',
            field=models.ManyToManyField(blank=True, to='constants.Position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='speciality',
            field=models.ManyToManyField(blank=True, null=True, to='constants.Speciality', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='work',
            field=models.ManyToManyField(blank=True, null=True, to='constants.Hospital', verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='additional_speciality',
            field=models.ManyToManyField(blank=True, null=True, related_name='extra_speciality', to='constants.Speciality', verbose_name='Дополнительные специальности'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constants.Area', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.ForeignKey(blank=True, default=17, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constants.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constants.City', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='curing_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constants.CuringForm', verbose_name='Форма лечения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date(1970, 1, 1), null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(default=' ', max_length=50, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='house',
            field=models.CharField(default=' ', max_length=12, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='constants.Position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constants.Speciality', verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='constants.Hospital', verbose_name='Место работы'),
        ),
    ]
