# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 22:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160106_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexchangehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 6, 0, 55, 37, 234489), verbose_name='Дата обмена'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='age_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст от'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='age_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст до'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='bed_quantity_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во койко-мест от'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='bed_quantity_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во койко-мест до'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='patient_quantity_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во пациентов в месяц от'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='patient_quantity_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во пациентов в месяц до'),
        ),
    ]
