# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170423_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[(' ', 'Выбрать...'), ('male', 'Мужчина'), ('female', 'Женщина')], default=' ', max_length=8, verbose_name='Пол'),
        ),
    ]
