# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 22:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160106_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexchangehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 6, 0, 58, 19, 557367), verbose_name='Дата обмена'),
        ),
    ]
