# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170423_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='house',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='patronimyc',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Отчество'),
        ),
    ]
