# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20170425_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='flat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='index',
            field=models.IntegerField(blank=True, null=True, verbose_name='Индекс'),
        ),
    ]
