# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 22:15
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170425_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(1970, 1, 1), verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
