# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 07:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20160106_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexchangehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 6, 9, 14, 8, 963298), verbose_name='Дата обмена'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('first', 'Первая'), ('second', 'Вторая'), ('no_category', 'Без категории')], default=' ', max_length=34, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='curing_form',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('stationar', 'Cтационарное'), ('poliklinika', 'Поликлиническое')], max_length=34, verbose_name='Форма лечения'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='gender',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=16, verbose_name='Пол'),
        ),
    ]
