# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 09:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20160106_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='exchange_score',
            field=models.IntegerField(default=0, verbose_name='Баллов обменяно'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='Баллов за всё время'),
        ),
        migrations.AlterField(
            model_name='userexchangehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 6, 11, 52, 43, 200258), verbose_name='Дата обмена'),
        ),
    ]
