# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 22:39
from __future__ import unicode_literals

from django.db import migrations, models


def forward(apps, schema_editor):
    UserProfile = apps.get_model("users", "UserProfile")
    for up in UserProfile.objects.all():
        if up.speciality:
            up.additional_speciality.add(up.speciality)

class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0001_initial'),
        ('users', '0011_auto_20170425_2216'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
