# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_userprofile_specialities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='additional_speciality',
            field=models.ManyToManyField(blank=True, null=True, related_name='extra_speciality', to='constants.Speciality', verbose_name='Специальность'),
        ),
    ]
