# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-14 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20170502_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilter',
            name='users',
            field=models.ManyToManyField(blank=True, to='users.UserProfile', verbose_name='Пользователи в группе'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='additional_speciality',
            field=models.ManyToManyField(blank=True, related_name='extra_speciality', to='constants.Speciality', verbose_name='Специальность'),
        ),
    ]
