# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20160106_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexchangehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 10, 21, 49, 19, 656661), verbose_name='Дата обмена'),
        ),
    ]
