# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20170514_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilter',
            name='users',
            field=models.ManyToManyField(blank=True, to='users.UserProfile', verbose_name='Отдельные пользователи'),
        ),
    ]
