# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0001_initial'),
        ('users', '0016_auto_20170515_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='extra_positions', to='constants.Position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='works',
            field=models.ManyToManyField(blank=True, related_name='extra_works', to='constants.Hospital', verbose_name='Место работы'),
        ),
    ]
