# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 16:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20160111_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexchangehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 27, 18, 10, 27, 530817), verbose_name='Дата обмена'),
        ),
    ]
