# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_migrate_work_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfilter',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('user__username',)},
        ),
    ]
