# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 12:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20160213_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexchangehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 13, 14, 16, 5, 546376), verbose_name='Дата обмена'),
        ),
    ]
