# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 12:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20160213_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexchangehistory',
            name='day',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата обмена'),
        ),
        migrations.AlterField(
            model_name='userexchangehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 14, 14, 40, 34, 632918), verbose_name='Дата обмена'),
        ),
    ]
