# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-14 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20160214_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexchangehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 14, 16, 28, 21, 430706), verbose_name='Дата обмена'),
        ),
        migrations.AlterField(
            model_name='userexchangehistory',
            name='day',
            field=models.DateField(default=datetime.datetime(2016, 2, 14, 14, 28, 21, 430706, tzinfo=utc), verbose_name='Дата обмена'),
        ),
    ]
