# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20160215_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField(verbose_name='Длительность сеанса')),
                ('time', models.DateTimeField(default=datetime.datetime(2016, 2, 19, 13, 27, 57, 735819), verbose_name='Время сеанса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='userexchangehistory',
            name='day',
        ),
        migrations.AlterField(
            model_name='userexchangehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 19, 13, 27, 57, 735319), verbose_name='Дата обмена'),
        ),
    ]
