# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 11:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20160219_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexchangehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 19, 13, 38, 18, 196849), verbose_name='Дата обмена'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='duration',
            field=models.DurationField(verbose_name='Длительность сеанса'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 19, 13, 38, 18, 197350), verbose_name='Время сеанса'),
        ),
    ]
