# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20160219_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexchangehistory',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обмена'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время сеанса'),
        ),
    ]
