# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0004_category_curingform'),
        ('users', '0031_auto_20160224_1427'),
    ]

    operations = [

        migrations.AddField(
            model_name='userfilter',
            name='category',
            field=models.ManyToManyField(blank=True, default=None, to='constants.Category', verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constants.Category', verbose_name='Категория'),
        ),

        migrations.AddField(
            model_name='userfilter',
            name='curing_form',
            field=models.ManyToManyField(blank=True, default=None, to='constants.CuringForm', verbose_name='Форма лечения'),
        ),
        migrations.AlterField(
            model_name='userfilter',
            name='position',
            field=models.ManyToManyField(blank=True, default=None, related_name='_userfilter_position_+', to='constants.Position', verbose_name='Должность'),
        ),

        migrations.AddField(
            model_name='userprofile',
            name='curing_form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='constants.CuringForm', verbose_name='Форма лечения'),
        ),
    ]
