# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0004_category_curingform'),
        ('users', '0032_auto_20160229_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='constants.Position', verbose_name='Должность'),
        ),
    ]
