# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_userprofile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilter',
            name='users',
            field=models.ManyToManyField(null=True, to='users.UserProfile', verbose_name='Пользователи в группе'),
        ),
    ]
