# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_userfilter_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfilter',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='users.UserProfile', verbose_name='Пользователи в группе'),
        ),
    ]
