# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0004_category_curingform'),
        ('users', '0035_auto_20160229_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfilter',
            name='area',
            field=models.ManyToManyField(blank=True, default=' ', to='constants.Area', verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='userfilter',
            name='city',
            field=models.ManyToManyField(blank=True, default=' ', to='constants.City', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='userfilter',
            name='position',
            field=models.ManyToManyField(blank=True, default=None, related_name='_userfilter_position_+', to='constants.Position', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='userfilter',
            name='speciality',
            field=models.ManyToManyField(blank=True, default=' ', to='constants.Speciality', verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='userfilter',
            name='work',
            field=models.ManyToManyField(blank=True, default=' ', to='constants.Hospital', verbose_name='Место работы'),
        ),
    ]
