# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160106_0058'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='user_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.UserFilter', verbose_name='Для какой группы назначен опрос'),
        ),
    ]
