# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 15:48
from __future__ import unicode_literals

from django.db import migrations




def forward(apps, schema_editor):
    Poll = apps.get_model("polls", "Poll")
    for poll in Poll.objects.all():
        if poll.user_group:
           poll.user_groups.add(poll.user_group)

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_user_groups'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
