# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 07:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20160106_0951'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userspoll',
            unique_together=set([('user', 'poll')]),
        ),
    ]
