# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 16:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170330_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='user_group',
        ),
    ]
