# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170331_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения опроса'),
        ),
    ]
