# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20160106_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspoll',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='Пройдено'),
        ),
    ]
