# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_userspoll_passed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspoll',
            name='passed',
            field=models.NullBooleanField(default=False, verbose_name='Пройдено'),
        ),
    ]
