# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20160107_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspoll',
            name='passed',
            field=models.BooleanField(default=False, verbose_name='Пройдено'),
        ),
        migrations.AlterField(
            model_name='userspoll',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smth', to='polls.Poll', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='userspoll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='Пользователь'),
        ),
    ]
