# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20160107_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(max_length=150, verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=450, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, max_length=1450, verbose_name='Текст перед вопросом'),
        ),
    ]
