# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20170502_1241'),
        ('polls', '0010_auto_20170424_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='separate_users',
            field=models.ManyToManyField(blank=True, related_name='separate_user', to='users.UserProfile', verbose_name='Отдельные пользователи'),
        ),
    ]
