# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_poll_separate_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения опроса'),
        ),
        migrations.AlterField(
            model_name='userpollfilter',
            name='polls',
            field=models.ManyToManyField(blank=True, to='polls.Poll', verbose_name='Конкретные опросы'),
        ),
        migrations.AlterField(
            model_name='userpollfilter',
            name='users',
            field=models.ManyToManyField(blank=True, to='users.UserProfile', verbose_name='Конкретные пользователи'),
        ),
    ]
