# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20160110_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, max_length=6550, verbose_name='Текст перед вопросом'),
        ),
    ]
