# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-14 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20170502_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='date_answered',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата ответа'),
        ),
    ]
