# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20160127_1810'),
        ('polls', '0014_auto_20160110_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='medicine',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.Medicine', verbose_name='Лекарство'),
        ),
    ]
