# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20160213_1410'),
        ('polls', '0017_auto_20160203_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Опрос'},
        ),
        migrations.RemoveField(
            model_name='poll',
            name='user_group',
        ),
        migrations.AddField(
            model_name='poll',
            name='user_group',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='users.UserFilter', verbose_name='Для какой группы назначен опрос'),
        ),
    ]
