# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20160213_1416'),
        ('polls', '0018_auto_20160213_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='user_group',
        ),
        migrations.AddField(
            model_name='poll',
            name='user_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserFilter', verbose_name='Для какой группы назначен опрос'),
        ),
    ]
