# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20160224_1427'),
        ('polls', '0019_auto_20160213_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPollFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата прохождения от')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата прохождения до')),
                ('order', models.CharField(choices=[('question__poll__id', 'По опросам'), ('user__user__id', 'По пользователям')], default='question__poll__id', max_length=25, verbose_name='Групировка')),
                ('group', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserFilter', verbose_name='Группа пользователей')),
            ],
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={},
        ),
        migrations.AddField(
            model_name='userspoll',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Оповещение отправлено'),
        ),
        migrations.AlterField(
            model_name='userspoll',
            name='date_assigned',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='userspoll',
            name='date_passed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата прохождения'),
        ),
        migrations.AddField(
            model_name='userpollfilter',
            name='polls',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Poll', verbose_name='Конкретные опросы'),
        ),
        migrations.AddField(
            model_name='userpollfilter',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='users.UserProfile', verbose_name='Конкретные пользователи'),
        ),
    ]
