# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20160215_1020'),
        ('polls', '0019_auto_20160213_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPollFilter',
            fields=[
                ('userfilter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.UserFilter')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Дата прохождения от')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Дата прохождения до')),
            ],
            bases=('users.userfilter',),
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={},
        ),
        migrations.AddField(
            model_name='userpollfilter',
            name='polls',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Poll', verbose_name='Конкретные опросы'),
        ),
        migrations.AddField(
            model_name='userpollfilter',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='users.UserProfile', verbose_name='Конкретные пользователи'),
        ),
    ]
