# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20160215_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpollfilter',
            name='order',
            field=models.CharField(choices=[('simple', 'Простой'), ('text', 'Текстовый')], default='poll', max_length=5),
        ),
    ]
