# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_userpollfilter_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpollfilter',
            name='order',
            field=models.CharField(choices=[('user', 'По пользователям'), ('poll', 'По опросам')], default='poll', max_length=5),
        ),
    ]
