# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_auto_20160303_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_text_ru',
            field=models.CharField(max_length=450, null=True, verbose_name='Вариант ответа'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_text_uk',
            field=models.CharField(max_length=450, null=True, verbose_name='Вариант ответа'),
        ),
    ]
