# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20160215_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpollfilter',
            name='order',
            field=models.CharField(choices=[('question__poll__id', 'По опросам'), ('user__user__id', 'По пользователям')], default='question__poll__id', max_length=25, verbose_name='Групировка'),
        ),
    ]
