# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20160219_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspoll',
            name='date_assigned',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='userspoll',
            name='date_passed',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата прохождения'),
        ),
    ]
