# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20160221_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspoll',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Оповещение отправлено'),
        ),
    ]
