# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True


    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст новости')),
                ('text_ru', models.TextField(max_length=2000, null=True, verbose_name='Текст новости')),
                ('text_uk', models.TextField(max_length=2000, null=True, verbose_name='Текст новости')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PollHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Краткое название')),
                ('name_ru', models.CharField(max_length=40, null=True, verbose_name='Краткое название')),
                ('name_uk', models.CharField(max_length=40, null=True, verbose_name='Краткое название')),
                ('text', models.TextField(max_length=2300, verbose_name='Краткое содержание')),
                ('text_ru', models.TextField(max_length=2300, null=True, verbose_name='Краткое содержание')),
                ('text_uk', models.TextField(max_length=2300, null=True, verbose_name='Краткое содержание')),
                ('date_assigned', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('user_group', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserFilter', verbose_name='Какой группе пользователей отправить текст')),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.PollHistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='pollhistory',
            name='users',
            field=models.ManyToManyField(through='history.UserHistory', to='users.UserProfile'),
        ),
    ]
