# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text_uk',
            field=models.TextField(null=True, verbose_name='Текст новости'),
        ),
        migrations.AlterField(
            model_name='pollhistory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Краткое название'),
        ),
        migrations.AlterField(
            model_name='pollhistory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Краткое название'),
        ),
        migrations.AlterField(
            model_name='pollhistory',
            name='name_uk',
            field=models.CharField(max_length=100, null=True, verbose_name='Краткое название'),
        ),
        migrations.AlterField(
            model_name='pollhistory',
            name='text',
            field=models.TextField(verbose_name='Краткое содержание'),
        ),
        migrations.AlterField(
            model_name='pollhistory',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Краткое содержание'),
        ),
        migrations.AlterField(
            model_name='pollhistory',
            name='text_uk',
            field=models.TextField(null=True, verbose_name='Краткое содержание'),
        ),
    ]
