# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 22:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160106_0058'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollhistory',
            name='user_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.UserFilter', verbose_name='Какой группе пользователей отправить текст'),
        ),
        migrations.AlterField(
            model_name='pollhistory',
            name='date_assigned',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 6, 0, 58, 24, 676292), verbose_name='Дата создания'),
        ),
    ]
