# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20170515_1001'),
        ('history', '0002_auto_20170423_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollhistory',
            name='separate_users',
            field=models.ManyToManyField(blank=True, related_name='separate_user_history', to='users.UserProfile', verbose_name='Отдельные пользователи'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='date_created',
            field=models.DateTimeField(null=True, verbose_name='Дата отправления'),
        ),
    ]
