# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20160106_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollhistory',
            name='date_assigned',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 6, 12, 46, 4, 179796), verbose_name='Дата создания'),
        ),
    ]
