# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20170515_1001'),
        ('history', '0003_auto_20170515_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(null=True, verbose_name='Дата отправления')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserFilter')),
            ],
        ),
        migrations.RemoveField(
            model_name='pollhistory',
            name='date_assigned',
        ),
        migrations.AddField(
            model_name='pollhistory',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего изменения'),
        ),
        migrations.AddField(
            model_name='grouphistory',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.PollHistory'),
        ),
        migrations.AddField(
            model_name='pollhistory',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='history_groups', through='history.GroupHistory', to='users.UserFilter', verbose_name='Какой группе пользователей отправить текст'),
        ),
    ]
