# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 20:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20160110_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollhistory',
            name='date_assigned',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 10, 22, 0, 31, 108517), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='pollhistory',
            name='user_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserFilter', verbose_name='Какой группе пользователей отправить текст'),
        ),
    ]
