# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20170515_1001'),
        ('history', '0005_migrate_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollhistory',
            name='user_groups',
        ),
        migrations.AddField(
            model_name='pollhistory',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='users.UserFilter', verbose_name='Группа'),
        ),
    ]
