# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_migrate_data_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouphistory',
            name='group',
        ),
        migrations.RemoveField(
            model_name='grouphistory',
            name='history',
        ),
        migrations.DeleteModel(
            name='GroupHistory',
        ),
    ]
