# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 21:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_auto_20160203_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollhistory',
            name='score',
        ),
        migrations.AlterField(
            model_name='pollhistory',
            name='date_assigned',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 3, 23, 44, 15, 254683), verbose_name='Дата создания'),
        ),
    ]
