# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0012_auto_20160221_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000, verbose_name='Текст новости')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
            ],
        ),
    ]
