# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0015_auto_20160315_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=models.TextField(max_length=2000, null=True, verbose_name='Текст новости'),
        ),
        migrations.AddField(
            model_name='pollhistory',
            name='name_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Краткое название'),
        ),
        migrations.AddField(
            model_name='pollhistory',
            name='text_en',
            field=models.TextField(max_length=2300, null=True, verbose_name='Краткое содержание'),
        ),
    ]
