# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 22:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        ('constants', '__first__'),
        ('history', '__first__'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название лекарства')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 1, 5, 0, 35, 9, 115710), verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[(' ', 'Выбрать...'), ('male', 'Мужчина'), ('female', 'Женщина')], max_length=8, verbose_name='Пол')),
                ('curing_form', models.CharField(blank=True, choices=[(' ', 'Выбрать...'), ('stationar', 'Cтационарное'), ('poliklinika', 'Поликлиническое')], max_length=15, verbose_name='Форма лечения')),
                ('category', models.CharField(blank=True, choices=[(' ', 'Выбрать...'), ('first', 'Первая'), ('second', 'Вторая'), ('no_category', 'Без категории')], default=' ', max_length=15, verbose_name='Категория')),
                ('age_from', models.IntegerField(blank=True, verbose_name='Возраст от')),
                ('age_to', models.IntegerField(blank=True, verbose_name='Возраст от')),
                ('bed_quantity_from', models.IntegerField(blank=True, verbose_name='Кол-во койко-мест от')),
                ('bed_quantity_to', models.IntegerField(blank=True, verbose_name='Кол-во койко-мест до')),
                ('patient_quantity_from', models.IntegerField(blank=True, verbose_name='Кол-во пациентов в месяц от')),
                ('patient_quantity_to', models.IntegerField(blank=True, verbose_name='Кол-во пациентов в месяц до')),
                ('area', models.ManyToManyField(blank=True, default=' ', to='constants.Area', verbose_name='Область')),
                ('city', models.ManyToManyField(blank=True, default=' ', to='constants.City', verbose_name='Город')),
                ('position', models.ManyToManyField(blank=True, default=' ', related_name='_userfilter_position_+', to='constants.Position', verbose_name='Должность')),
                ('speciality', models.ManyToManyField(blank=True, default=' ', to='constants.Speciality', verbose_name='Специальность')),
                ('user_group_history', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='history.PollHistory', verbose_name='Какой группе пользователей отправить текст')),
                ('user_group_polls', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='polls.Poll', verbose_name='Для какой группы назначен опрос')),
                ('work', models.ForeignKey(blank=True, default=' ', on_delete=django.db.models.deletion.CASCADE, to='constants.Hospital', verbose_name='Место работы')),
            ],
        ),
    ]
