# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 22:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfilter',
            name='area',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='position',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='user_group_history',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='user_group_polls',
        ),
        migrations.RemoveField(
            model_name='userfilter',
            name='work',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 6, 0, 51, 44, 483262), verbose_name='Дата создания'),
        ),
        migrations.DeleteModel(
            name='UserFilter',
        ),
    ]
