# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 07:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_auto_20160106_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 6, 9, 48, 54, 254531), verbose_name='Дата создания'),
        ),
    ]
