# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_auto_20160106_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 10, 21, 49, 19, 670170), verbose_name='Дата создания'),
        ),
    ]
