# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-27 16:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20160127_1810'),
        ('medicine', '0005_auto_20160110_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название лекарства')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 1, 27, 18, 10, 27, 542324), verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='date',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='user',
        ),
        migrations.AddField(
            model_name='medicine',
            name='instruction',
            field=models.TextField(blank=True, max_length=20000, verbose_name='Инструкция'),
        ),
    ]
