# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 12:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20160127_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 31, 14, 35, 29, 904587), verbose_name='Дата создания'),
        ),
    ]
