# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_auto_20160131_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 19, 13, 27, 57, 740324), verbose_name='Дата создания'),
        ),
    ]
