# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0002_category_curingform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='CuringForm',
        ),
    ]
