# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0004_category_curingform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название лечебного учреждения'),
        ),
    ]
